version: '3.1'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    network_mode: host
    ports:
      - "2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka-1:
    image: bitnami/kafka:latest
    network_mode: host
    ports:
      - "19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:19092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:19092
      KAFKA_CFG_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:19092
      ALLOW_PLAINTEXT_LISTENER: yes

  kafka-2:
    image: bitnami/kafka:latest
    network_mode: host
    ports:
      - "29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:29092
      KAFKA_CFG_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      ALLOW_PLAINTEXT_LISTENER: yes

  kafka-3:
    image: bitnami/kafka:latest
    network_mode: host
    ports:
      - "39092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_BROKER_ID: 3
      KAFKA_CFG_LISTENERS: PLAINTEXT://:39092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:39092
      KAFKA_CFG_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      ALLOW_PLAINTEXT_LISTENER: yes