name: CICD
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .