name: CICD
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run vet & lint
        run: |
          go vet .
          golint 
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .