name: CICD
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Linting
        uses: golangci/golangci-lint-action@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker build
        run: docker build . -t ${{secrets.DOCKER_USER}}/example-kafka-producer:${{GITHUB_SHA}}
      - name: Docker push tag
        run: docker push ${{secrets.DOCKER_USER}}/example-kafka-producer:${{GITHUB_SHA}}